### ISSUE TITLE
Strategy doesn't work

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#157]
**Describe the bug**
In addition to the chosen strategy, it also shows you other results

**Steps To Reproduce**
Java is selected and I also see c#

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/6cbc2c91-0b9c-45a4-ac40-e8220d9a8c57)
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/a560788a-71b7-4bac-a897-a296c749b70a)

**Additional context**

**Comment by Innos** [comment]
The search is by strategy, not by Contest names and the contest, does indeed allow the Java strategy. While it may be strange that a contest like "Advanced C# Exam Problems Practice" allows the Java strategy, it actually is sensible, especially for past contests, to be opened for strategies in other languages so that people can have more problems to practice.

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/12100545/33bc6038-2733-43a9-958c-20e5661e4899)

**Comment by VankoIvanov** [comment]
If you have an exercise "if you check" but java, python, js and C#. I think if I choose a java code it will show me If check - Java, not If check - Java, If check - C#, If check - JS, If check - python. So the user always gets results x4. And he is only excited about Java language exercises
