### ISSUE TITLE
Search users

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#162]
When search and find user is not possible to click and see the user's profile - no matter it searching for mine user or others.

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/c41c7b30-12ac-4247-82bb-36254b3de39c)

**Comment by Innos** [comment]
Sounds reasonable to have the user profile display something, otherwise the search itself is mostly pointless. In the current judge, normal users appear to be able see the contest participation of other users
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/12100545/81ca108a-ea87-4495-839b-54236ad9b026)
