### ISSUE TITLE
Resources suggestion

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#174]
Will be good as a static part of the contest tasks page resources to be always visible:
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/23dfe361-83db-49d9-983c-81b564418d1b)

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/63d69b7e-63f1-415e-a79e-a5aafd4df7fe)

**Comment by Innos** [comment]
The system supports per task resources, and as shown in this case we see a resource attached to the 1st problem, but we don't see any resources on the second problem as it doesn't have any attached to it. The general reason is that contests started to be made with all problems in a single file attached to the first task, so in terms of issues this is working as intended.

I'll keep this as a recommendation though, since the above mentioned is the current de facto way to use the system, it is not a bad recommendation that maybe the system should also start supporting contest wide attachments, in addition to problem wide attachments, but this will need further discussion.

**Comment by Innos** [comment]
I'm removing the Recommendation label and leaving it as a normal issue, having the ability to attach documents to the contest level instead of the problem level, seems to be a reasonable idea, given the de facto current usage of the system. Though this change is probably really low priority, as I would imagine once you've opened the tasks document, you would very rarely need to reopen it, but still, it is a slight UX improvement.
