### ISSUE TITLE
On search responsive design

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#207]
**Describe the bug**
When searching and minimized, the results are not centered. There is more space on the right

**Steps To Reproduce**

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/9cfe0a09-1c7a-40e7-bb62-5bb7550945ea)

**Additional context**

**Comment by Innos** [comment]
Certain specific screen widths (have to check if these are actual device widths), lead to having extra margin after the boxes, since the boxes probably have a min-width, "justify-content: center" can be used, but it will lead cases where boxes might group in the center with leftover boxes. In the end I'll leave this as a UI recommendation, but it might be very subjective, which case is better. 
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/12100545/4ee5f6fa-ed46-4bff-8056-897e59c4f73f)

**Comment by Innos** [comment]
Connecting this as a potential sub issue to the Responsive design issue: https://github.com/SoftUni-Internal/hackathon-issues/issues/193
